name: 'CI'

on:
  push:
    branches:
      - feature/github_workflow
  workflow_dispatch:
    
jobs:
  deployment-of-b-book-compose:
    runs-on: ubuntu-letes

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: feature/github_workflow 
        
      - name: install dependencies
        run:  npm ci
      - name: lint 
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build