name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build application
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image frontend
      run: |
        cd frontend
        docker build . --file Dockerfile --tag aws2307/budgetbook-frontend:0.0.1
        docker push aws2307/budgetbook-frontend:0.0.1

    - name: Build and push Docker image auth
      run: |
        cd auth
        docker build . --file Dockerfile --tag aws2307/budgetbook-auth:0.0.1
        docker push aws2307/budgetbook-auth:0.0.1
