name: frontend

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    name: Build and Test Frontend
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: feature/github_workflow

      - name: Install dependencies
        run: npm install

      - name: Build frontend application
        run: npm run build

      - name: Lint frontend code
        run: npm run lint