name: statistics

on:
  push:
    branches:
      - 'main'

jobs:
  build_statistics:
    runs-on: ubuntu-latest
    name: Build and Test statistics
    defaults:
      run:
        working-directory: ./statistics

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Build backend application
        run: npm run build

      - name: Lint backend code
        run: npm run lint